services:
  - type: web
    name: quotes_insurance
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn quotes_insurance.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
