# Generated by Django 5.2.7 on 2026-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=150)),
                ('homepage_title', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_tagline', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicon/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
