# Generated by Django 5.2.7 on 2026-01-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainpage_dropdownitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
