# Generated by Django 5.2.7 on 2026-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownitem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/og/'),
        ),
    ]
