# Generated by Django 5.2.7 on 2026-01-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dropdownitem_content_dropdownitem_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownitem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='dropdownitem',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='dropdownitem',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='dropdownitem',
            name='meta_title',
        ),
    ]
