# Generated by Django 5.2.7 on 2026-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dropdownitem_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownitem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
