# Generated by Django 5.2.7 on 2026-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dropdownitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownitem',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='dropdown/hero/'),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/hero/'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
