# Generated by Django 5.2.7 on 2026-01-17 13:22

from django.db import migrations

def fix_urls(apps, schema_editor):
    MainPage = apps.get_model("core", "MainPage")
    DropdownItem = apps.get_model("core", "DropdownItem")

    # Fix Main Pages
    # Convert '#' to '' so they use get_absolute_url
    MainPage.objects.filter(url="#").update(url="")

    # Fix Dropdown Items
    # Convert '#' to '' so they use get_absolute_url
    DropdownItem.objects.filter(url="#").update(url="")

    # Specific fix for "Contact Us" dropdown item under "About Us"
    # It should link to the main contact page
    contact_page = MainPage.objects.filter(slug="contact-us").first()
    if contact_page:
        contact_url = f"/p/{contact_page.slug}/"
        DropdownItem.objects.filter(title="Contact Us", main_page__title="About Us").update(url=contact_url)

def reverse_fix(apps, schema_editor):
    # No need to reverse, strictly speaking, but we could put # back if we wanted.
    # For now, let's leave it as is.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dropdownitem_hero_image_dropdownitem_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_urls, reverse_fix),
    ]
