# Generated by Django 5.2.7 on 2026-01-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fix_seed_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='show_in_navbar',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from top navigation bar'),
        ),
    ]
