# Generated by Django 5.2.7 on 2026-01-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_quote_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payments/logos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Partner',
                'verbose_name_plural': 'Payment Partners',
                'ordering': ['order'],
            },
        ),
    ]
