# Generated by Django 5.2.7 on 2026-01-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_atlas_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('fein', models.CharField(blank=True, max_length=50, verbose_name='FEIN')),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_address', models.CharField(blank=True, max_length=100, verbose_name='State / Province / Region')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP / Postal Code')),
                ('is_new_business', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('description_of_operation', models.TextField(blank=True)),
                ('cities_of_operation', models.TextField(blank=True, verbose_name='Cities where vehicles regularly operate')),
                ('operate_state', models.CharField(blank=True, max_length=100, verbose_name='What state do you operate in?')),
                ('number_of_losses', models.PositiveIntegerField(blank=True, default=0)),
                ('loss_runs_file', models.FileField(blank=True, null=True, upload_to='quotes/loss_runs/')),
                ('is_currently_insured', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=20, verbose_name='Are you currently insured?')),
                ('current_carrier', models.CharField(blank=True, max_length=200)),
                ('radius_of_operation', models.CharField(blank=True, max_length=100)),
                ('years_in_business', models.PositiveIntegerField(blank=True, null=True)),
                ('general_liability_needed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('general_liability_limits', models.CharField(blank=True, max_length=100)),
                ('auto_liability_limits', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotes/misc_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.quoterequest')),
            ],
        ),
    ]
