# Generated by Django 5.2.7 on 2026-01-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quoterequest_quoterequestdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('operate_state', models.CharField(blank=True, max_length=100, verbose_name='What state do you operate in?')),
                ('driver_change_type', models.CharField(blank=True, max_length=20, verbose_name='Driver Change Action')),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_dob', models.DateField(blank=True, null=True, verbose_name='Driver DOB')),
                ('driver_license', models.CharField(blank=True, max_length=100)),
                ('vehicle_change_type', models.CharField(blank=True, max_length=20, verbose_name='Vehicle Change Action')),
                ('vehicle_year', models.CharField(blank=True, max_length=20)),
                ('vehicle_make_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_vin', models.CharField(blank=True, max_length=100, verbose_name='VIN Number')),
                ('vehicle_coverage', models.CharField(blank=True, max_length=20, verbose_name='Comp or Collision coverage?')),
                ('vehicle_value', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
