# Generated by Django 5.2.7 on 2026-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fileuploadrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('operate_state', models.CharField(blank=True, max_length=100, verbose_name='What state do you operate in?')),
                ('message', models.TextField(verbose_name='How can we help?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
