# Generated by Django 5.2.7 on 2026-01-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_faqcategory_faqsubcategory_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insurance Coverage Type',
                'verbose_name_plural': 'Insurance Coverage Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('coverages', models.ManyToManyField(blank=True, related_name='products', to='core.insurancecoveragetype')),
                ('dropdown_item', models.OneToOneField(blank=True, help_text='Link this product to a site page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_product', to='core.dropdownitem')),
            ],
            options={
                'verbose_name': 'Insurance Product',
                'verbose_name_plural': 'Insurance Products',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='insurance_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_categories', to='core.insuranceproduct'),
        ),
    ]
