# Generated by Django 5.2.7 on 2026-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_insurancecoveragetype_insuranceproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='faqsubcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='faqcategory',
            unique_together={('insurance_product', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='faqsubcategory',
            unique_together={('category', 'slug')},
        ),
    ]
