# Generated by Django 5.2.7 on 2026-01-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_faqcategory_slug_faqsubcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='coverages',
            field=models.ManyToManyField(blank=True, related_name='faq_categories', to='core.insurancecoveragetype'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='dropdown_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_category', to='core.dropdownitem'),
        ),
    ]
