# Generated by Django 5.2.7 on 2026-01-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_link_products_to_dropdown_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
