# Generated by Django 5.2.7 on 2026-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_backfill_dropdownitem_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('Email', 'via Email'), ('Phone', 'via Phone'), ('Online', 'Online')], max_length=20, verbose_name='Preferred contact method'),
        ),
    ]
