# Generated by Django 5.2.7 on 2026-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='coming_soon_states_list',
            field=models.TextField(blank=True, help_text='Comma-separated list of states coming soon (e.g. Alabama, Arkansas)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='serving_states_list',
            field=models.TextField(blank=True, help_text='Comma-separated list of states currently serving (e.g. Alaska, Arizona, California)'),
        ),
    ]
