# Generated by Django 5.2.7 on 2026-01-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_siteconfig_coming_soon_states_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Check to display this page as a service card on the homepage'),
        ),
    ]
