# Generated by Django 5.2.7 on 2026-01-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_mainpage_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_about_content',
            field=models.TextField(blank=True, default="Figuring out the ins and outs of insurance coverage for different types of transportation companies in different states can be complicated. Requirements can vary greatly depending on the type of business you operate, where you're located, and other specific factors. Insurance is an important investment, so don't cut corners and put your business, drivers, and passengers at risk!\n\nIf your business is in one of the states we're currently serving, our team of specialized insurance agents will know just the type of insurance coverage you need to protect every aspect of your business. Whatever your insurance needs may be, we can put together a fair quote for you, delivered with excellent customer service. We offer quick processing of certificate and AI requests, multiple points of contact, quick quote turnaround, and solution- based thinking for all your insurance needs! You can rest assured knowing that OTTIS is on your side and has you covered.", help_text='Content for the About section on the homepage'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_about_title',
            field=models.CharField(blank=True, default='About Oswald Taxi and Transportation Services', help_text='Title for the About section on the homepage', max_length=200),
        ),
    ]
