# Generated by Django 5.2.7 on 2026-01-31 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_siteconfig_home_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='dropdown_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.dropdownitem'),
        ),
        migrations.AddField(
            model_name='relatedarticle',
            name='dropdown_items',
            field=models.ManyToManyField(blank=True, related_name='related_articles', to='core.dropdownitem'),
        ),
    ]
