# Generated by Django 5.2.7 on 2026-01-31 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_customerreview_dropdown_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='dropdownitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='show_in_navbar',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show this FAQ item on the home page'),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='content_width',
            field=models.CharField(choices=[('container', 'Container'), ('full', 'Full Width')], default='container', max_length=20),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='description',
            field=models.CharField(blank=True, help_text='Short description for menu/cards', max_length=255),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG code for icon'),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dropdown/images/'),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='layout_columns',
            field=models.PositiveIntegerField(choices=[(1, '1 Column'), (2, '2 Columns')], default=1),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='content_width',
            field=models.CharField(choices=[('container', 'Container'), ('full', 'Full Width')], default='container', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='layout_columns',
            field=models.PositiveIntegerField(choices=[(1, '1 Column'), (2, '2 Columns')], default=1),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='home_about_content',
            field=models.TextField(blank=True, default='We are a leading provider of taxi and transportation insurance...', help_text='Content for the About section on the homepage'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
