# Generated by Django 5.2.7 on 2026-01-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_blogcategory_alter_dropdownitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.faqcategory'),
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
